### ISSUE TITLE
Trouble installing 

### ISSUE THREAD

**Issue by Eduardogit** [penk/qml-livereload#4]
I am very new in Qt, The thing is that i compile the first .pro (that is livereload.pro)  inside qml-livereload folder on QT 5 but i don't know how  can i run it, also i don't know what to do with File IO folder/files.
Where i can see a tutorial or something ? 
Thanks

**Comment by sawyerlin** [comment]
to compile it, you should have at least **qt5-make** installed

so clone the project into **/tmp**

then enter the folder **/tmp/qml-liveload**

run qmake && make

as we already modified the file livereload.pro with:

TARGET = /usr/local/bin/qmllive

when the make is done, you could use **qmllive** in your terminal as **qmlscene** to run a qml file.

hope this helps

**Comment by Eduardogit** [comment]
Of course thanks !
